#!/usr/bin/env bash
# This script configures an Ubuntu server with requirements
sudo cp /etc/hosts ~/temp
sudo sed -i '/127.0.0.1\s\+localhost/s/127.0.0.1/127.0.0.2/' ~/temp
if ! grep -q "8.8.8.8 facebook.com" ~/temp; then
  echo "8.8.8.8 facebook.com" | sudo tee -a ~/temp > /dev/null
fi
sudo cp -f ~/temp /etc/hosts
rm ~/temp
